# Generated by Django 4.2.6 on 2023-10-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creation_time',
            field=models.TimeField(blank=True),
        ),
    ]
